### ISSUE TITLE
Error with subliminal

### ISSUE THREAD

**Issue by nuukcillo** [alombarte/raspberry-osmc-automated#6] opened 2016-02-16 20:06 UTC
hello I am getting this error trying to execute subliminal.

```
File "/usr/local/bin/subliminal", line 7, in <module>
    from subliminal.cli import subliminal
  File "/usr/local/lib/python2.7/dist-packages/subliminal/__init__.py", line 10, in <module>
    from .api import (ProviderPool, check_video, provider_manager, download_best_subtitles, download_subtitles,
  File "/usr/local/lib/python2.7/dist-packages/subliminal/api.py", line 13, in <module>
    from .subtitle import compute_score, get_subtitle_path
  File "/usr/local/lib/python2.7/dist-packages/subliminal/subtitle.py", line 7, in <module>
    from guessit.matchtree import MatchTree
ImportError: No module named matchtree
```

I got more error but i fixed them manually. I am running the script i a RPi2 B+

**Comment by alombarte** [comment] 2016-02-17 22:04
Where is this subliminal coming from? Have you executed the whole installation process? What is the version of OSMC that you are using?

**Comment by nuukcillo** [comment] 2016-02-18 08:22
It was a bug with my subliminal version which I downloaded from here. I fixed this yesterday upgrading it to lastest version. 

[Here](https://github.com/Diaoul/subliminal/issues/568) is the source and solution.

I forgot to mention I had to upgrade flexget because it won't work with the keyword "find:"

**Comment by alombarte** [comment] 2016-02-20 21:03
Thanks @nuukcillo for pointing to the solution. The installation is executed via a `pip install subliminal`, so the version downloaded will be different depending on when this is executed. I prefer to rely on the stability of all external packages rather than fixing the installation to a specific versions so this project evolves as the rest of the packages. Non fixing versions has the trade-off that if a maintainer screws the package this project will be also broken.

I am closing the task because the problem is unrelated to the coding of the installation script itself. But feel free to open another bug for the `find` issue, although I don't understand it now:

When you say the `find:` doesn't work anymore, are you referring to the config.yml file? If that's the case, what are you using now to cover the same functionality? I appreciate your contribution.

Thanks

**Closed as completed by alombarte** 2016-02-20 21:03 UTC

**Comment by nuukcillo** [comment] 2016-02-23 12:47
Hello,

for the `find:` word i mean, I had to upgrade flexblox with`pip install --upgrade flexget`, after getting last version It started to work.
